name: Deploy on dev server
on:
  push:
    branches: [ main ]
      

jobs:
  redeploying:
    runs-on: ubuntu-latest
    name: re-Deploying whole app to development environment
    steps: 
    - run: | 
        echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
        chmod 700 /home/runner/ssh_key
        ssh -oStrictHostKeyChecking=no -i ~/ssh_key root@64.227.162.230 -t "cd /root/DevOps && git pull origin main && export PATH=/root/.nvm/versions/node/v24.18.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin && npm install pnpm && pnpm install && pnpm run build && pm2 restart fe-server && pm2 restart ws-server && pm2 restart http-server"
        
        
        
        
        